"use client";

import { useMemo, useState } from "react";

const REPO = "asharara88/polyai";

const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);

export default function NewClientForm({ verticals }: { verticals: string[] }) {
  const [displayName, setDisplayName] = useState("");
  const [slug, setSlug] = useState("");
  const [vertical, setVertical] = useState(verticals[0] ?? "");
  const [primaryMarket, setPrimaryMarket] = useState("");
  const [primaryLang, setPrimaryLang] = useState("en");
  const [offering, setOffering] = useState("");
  const [voiceWords, setVoiceWords] = useState("");

  const effectiveSlug = slug || slugify(displayName);

  const profile = useMemo(
    () =>
      `# Client profile — ${displayName || "<client name>"}\n\n` +
      `> Generated by the new-client form. Refine after intake conversation; route updates through the \`knowledge\` agent.\n\n` +
      "```yaml\n" +
      `slug: ${effectiveSlug}\n` +
      `display_name: ${displayName || "<client name>"}\n` +
      `vertical: ${vertical}\n` +
      `markets:\n` +
      `  primary: ${primaryMarket || "# TODO"}\n` +
      `  secondary: []\n` +
      `languages:\n` +
      `  primary: ${primaryLang}\n` +
      `  secondary: []\n` +
      `offerings:\n` +
      `  - ${offering || "# TODO"}\n` +
      `business_model: # TODO\n` +
      `sales_motion: # TODO\n` +
      `typical_deal_cycle_days: # TODO\n` +
      `typical_deal_size: # TODO\n` +
      `icp_segments_ref: clients/${effectiveSlug}/knowledge/icp.md\n` +
      `brand_voice_ref: clients/${effectiveSlug}/knowledge/brand-voice.md\n` +
      `integrations:\n` +
      `  crm: # TODO\n` +
      `  ad_platforms: []\n` +
      `  email_platform: # TODO\n` +
      `  analytics: # TODO\n` +
      `  other: []\n` +
      `approval_gates:\n` +
      `  outbound_email_threshold: 0\n` +
      `  social_publish: always-approve\n` +
      `  paid_spend_cap: 0\n` +
      `  proposal_send: always-approve\n` +
      `  contract_signature: always-approve\n` +
      `compliance_flags: []\n` +
      `exclusions: []\n` +
      `status: onboarding\n` +
      `engagement_start: ${new Date().toISOString().slice(0, 10)}\n` +
      `engagement_end: null\n` +
      `notes: |\n` +
      `  Voice words: ${voiceWords || "# TODO"}\n` +
      "```\n",
    [displayName, effectiveSlug, vertical, primaryMarket, primaryLang, offering, voiceWords],
  );

  const githubNewFileUrl = useMemo(() => {
    const base = `https://github.com/${REPO}/new/main`;
    const params = new URLSearchParams({
      filename: `clients/${effectiveSlug}/client-profile.md`,
      value: profile,
      message: `Add client: ${effectiveSlug}`,
    });
    return `${base}?${params.toString()}`;
  }, [effectiveSlug, profile]);

  const ready = displayName && effectiveSlug && vertical;

  return (
    <div className="grid lg:grid-cols-2 gap-6">
      <form className="space-y-3 text-sm">
        <Field label="Display name (e.g. Acme Realty)">
          <input
            value={displayName}
            onChange={(e) => {
              setDisplayName(e.target.value);
              if (!slug) setSlug("");
            }}
            className="w-full rounded-md border border-ink-200/70 dark:border-ink-800 bg-white dark:bg-ink-900 px-3 py-2"
            placeholder="Acme Realty"
          />
        </Field>
        <Field label="Slug (auto from name; override if needed)">
          <input
            value={slug || slugify(displayName)}
            onChange={(e) => setSlug(slugify(e.target.value))}
            className="w-full rounded-md border border-ink-200/70 dark:border-ink-800 bg-white dark:bg-ink-900 px-3 py-2 font-mono"
            placeholder="acme-realty"
          />
        </Field>
        <Field label="Vertical">
          <select
            value={vertical}
            onChange={(e) => setVertical(e.target.value)}
            className="w-full rounded-md border border-ink-200/70 dark:border-ink-800 bg-white dark:bg-ink-900 px-3 py-2"
          >
            {verticals.map((v) => (
              <option key={v} value={v}>
                {v}
              </option>
            ))}
          </select>
        </Field>
        <Field label="Primary market (country/region)">
          <input
            value={primaryMarket}
            onChange={(e) => setPrimaryMarket(e.target.value)}
            className="w-full rounded-md border border-ink-200/70 dark:border-ink-800 bg-white dark:bg-ink-900 px-3 py-2"
            placeholder="AE"
          />
        </Field>
        <Field label="Primary language">
          <input
            value={primaryLang}
            onChange={(e) => setPrimaryLang(e.target.value)}
            className="w-full rounded-md border border-ink-200/70 dark:border-ink-800 bg-white dark:bg-ink-900 px-3 py-2 font-mono"
            placeholder="en"
          />
        </Field>
        <Field label="What they sell (one line)">
          <input
            value={offering}
            onChange={(e) => setOffering(e.target.value)}
            className="w-full rounded-md border border-ink-200/70 dark:border-ink-800 bg-white dark:bg-ink-900 px-3 py-2"
            placeholder="branded residences off-plan"
          />
        </Field>
        <Field label="Voice — three words">
          <input
            value={voiceWords}
            onChange={(e) => setVoiceWords(e.target.value)}
            className="w-full rounded-md border border-ink-200/70 dark:border-ink-800 bg-white dark:bg-ink-900 px-3 py-2"
            placeholder="precise, restrained, confident"
          />
        </Field>

        <div className="pt-2 flex flex-wrap items-center gap-3">
          <a
            href={ready ? githubNewFileUrl : "#"}
            target="_blank"
            rel="noopener"
            aria-disabled={!ready}
            onClick={(e) => {
              if (!ready) e.preventDefault();
            }}
            className={`rounded-md px-4 py-2 text-sm font-medium ${
              ready ? "bg-accent text-white" : "bg-ink-200 text-ink-500 cursor-not-allowed"
            }`}
          >
            Open in GitHub →
          </a>
          <button
            type="button"
            onClick={() => navigator.clipboard.writeText(profile)}
            disabled={!ready}
            className="text-xs font-mono text-ink-500 hover:text-ink-800 dark:hover:text-ink-200 disabled:opacity-50"
          >
            copy yaml
          </button>
        </div>
      </form>

      <div className="rounded-lg border border-ink-200/70 dark:border-ink-800 bg-white dark:bg-ink-900 p-4 max-h-[70vh] overflow-auto">
        <div className="text-xs font-mono text-ink-400 mb-2">
          clients/{effectiveSlug || "<slug>"}/client-profile.md
        </div>
        <pre className="text-xs leading-relaxed whitespace-pre-wrap font-mono">{profile}</pre>
      </div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="text-xs font-mono text-ink-400">{label}</span>
      <div className="mt-1">{children}</div>
    </label>
  );
}
