#!/usr/bin/env node
// Per-client public-source scan. Runs in GitHub Actions on a schedule.
// Reads clients/<slug>/monitoring.yml (optional) for client-specific sources.
// Falls back to the vertical's default sources from verticals/<vertical>/monitoring.yml.
// Writes a dated snapshot to clients/<slug>/knowledge/monitoring/<YYYY-MM-DD>.md.
//
// Pure scrape + commit. No LLM calls. The agents in Claude Code (or the chat UI) do the analysis.

import fs from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(process.cwd());

const today = () => new Date().toISOString().slice(0, 10);

const fetchText = async (url) => {
  const r = await fetch(url, {
    headers: {
      "user-agent":
        "Mozilla/5.0 (compatible; POLYAI-monitor/0.1; +https://github.com/asharara88/polyai)",
    },
  });
  if (!r.ok) throw new Error(`${r.status} ${r.statusText}`);
  return await r.text();
};

const stripHtml = (html) =>
  html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const summarize = (text, max = 1200) => {
  const t = text.length > max ? text.slice(0, max) + "…" : text;
  return t;
};

const parseSourcesYaml = (raw) => {
  // tiny YAML subset: lines like "- url: ..." with optional "- name: ..."
  const sources = [];
  let current = null;
  for (const line of raw.split("\n")) {
    const m = line.match(/^\s*-\s*url:\s*(.+)$/);
    if (m) {
      if (current) sources.push(current);
      current = { url: m[1].trim().replace(/^['"]|['"]$/g, ""), name: m[1].trim() };
      continue;
    }
    const n = line.match(/^\s+name:\s*(.+)$/);
    if (n && current) current.name = n[1].trim().replace(/^['"]|['"]$/g, "");
  }
  if (current) sources.push(current);
  return sources;
};

const readSources = async (clientSlug, vertical) => {
  // 1. clients/<slug>/monitoring.yml
  const clientFile = path.join(ROOT, "clients", clientSlug, "monitoring.yml");
  try {
    return parseSourcesYaml(await fs.readFile(clientFile, "utf8"));
  } catch {}
  // 2. verticals/<vertical>/monitoring.yml
  if (vertical) {
    const vfile = path.join(ROOT, "verticals", vertical, "monitoring.yml");
    try {
      return parseSourcesYaml(await fs.readFile(vfile, "utf8"));
    } catch {}
  }
  return [];
};

const readClientVertical = async (clientSlug) => {
  const profilePath = path.join(ROOT, "clients", clientSlug, "client-profile.md");
  try {
    const raw = await fs.readFile(profilePath, "utf8");
    const m = raw.match(/^vertical:\s*(.+)$/m);
    return m ? m[1].trim() : null;
  } catch {
    return null;
  }
};

const listClientSlugs = async () => {
  const top = path.join(ROOT, "clients");
  const out = [];
  try {
    const entries = await fs.readdir(top, { withFileTypes: true });
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      if (e.name === "_template" || e.name === "_examples") continue;
      out.push(e.name);
    }
    // include _examples for the demo
    const ex = path.join(top, "_examples");
    try {
      const exEntries = await fs.readdir(ex, { withFileTypes: true });
      for (const e of exEntries) {
        if (e.isDirectory()) out.push(`_examples/${e.name}`);
      }
    } catch {}
  } catch {}
  return out;
};

const scanClient = async (clientPath) => {
  const slug = clientPath;
  const isExample = clientPath.startsWith("_examples/");
  const vertical = await readClientVertical(slug);
  const sources = await readSources(slug, vertical);
  if (sources.length === 0) {
    console.log(`[${slug}] no sources configured, skipping`);
    return;
  }

  const findings = [];
  for (const s of sources) {
    try {
      const html = await fetchText(s.url);
      const text = stripHtml(html);
      findings.push({ name: s.name, url: s.url, status: "ok", excerpt: summarize(text) });
      console.log(`[${slug}] ok: ${s.url}`);
    } catch (e) {
      findings.push({ name: s.name, url: s.url, status: "error", excerpt: e.message });
      console.log(`[${slug}] error: ${s.url} (${e.message})`);
    }
  }

  const date = today();
  const lines = [
    `# Monitoring snapshot — ${slug} — ${date}`,
    "",
    `> Generated by \`monitoring/scan.mjs\` running in GitHub Actions. Raw scrape only.`,
    `> Hand off to \`competitive-intel\`, \`voc\`, or \`research\` (in Claude Code or the chat UI) for analysis.`,
    "",
    `Vertical: ${vertical ?? "—"}`,
    `Sources scanned: ${findings.length}`,
    "",
  ];
  for (const f of findings) {
    lines.push(`## ${f.name}`);
    lines.push("");
    lines.push(`- url: ${f.url}`);
    lines.push(`- status: ${f.status}`);
    lines.push("");
    lines.push("```");
    lines.push(f.excerpt);
    lines.push("```");
    lines.push("");
  }

  const outDir = path.join(ROOT, "clients", slug, "knowledge", "monitoring");
  await fs.mkdir(outDir, { recursive: true });
  const outFile = path.join(outDir, `${date}.md`);
  await fs.writeFile(outFile, lines.join("\n"), "utf8");
  console.log(`[${slug}] wrote ${path.relative(ROOT, outFile)}`);
};

const main = async () => {
  const slugs = await listClientSlugs();
  if (slugs.length === 0) {
    console.log("no clients found, nothing to do");
    return;
  }
  for (const slug of slugs) {
    try {
      await scanClient(slug);
    } catch (e) {
      console.error(`[${slug}] failed:`, e.message);
    }
  }
};

await main();
